# Generated by Django 4.1.6 on 2023-02-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='dCsnU+e%mm8_B0_3', max_length=200),
        ),
    ]
