# Generated by Django 4.1.6 on 2023-02-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('Can_cancel_publication_status_product', 'Can cancel publication status product'), ('Can_change_description_product', 'Can change description product'), ('Can_change_category_product', 'Can change category product')]},
        ),
        migrations.AddField(
            model_name='product',
            name='publication_status',
            field=models.BooleanField(default=True),
        ),
    ]
